# Generated by Django 3.1.7 on 2021-04-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='analyzed_data',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=1000)),
                ('json', models.JSONField()),
                ('csv_link', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('download', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='data_set',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('dataID', models.IntegerField(default=0)),
                ('categoryID', models.IntegerField(default=0)),
                ('userID', models.IntegerField(default=0)),
                ('analyzedDataID', models.IntegerField(default=0)),
            ],
        ),
    ]
