# Generated by Django 3.1.7 on 2021-05-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_set',
            name='typeID',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='data_set',
            name='categoryID',
            field=models.IntegerField(default=1),
        ),
    ]
