# Generated by Django 3.1.7 on 2021-03-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_list',
            name='建方予定日',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='products_list',
            name='記録日',
            field=models.CharField(default='', max_length=100),
        ),
    ]
