# Generated by Django 3.1.7 on 2021-05-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processApp', '0002_auto_20210510_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_set',
            name='linkFolder',
            field=models.TextField(default=''),
        ),
    ]
