# Generated by Django 3.1.7 on 2021-03-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processApp', '0002_auto_20210326_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_process',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('product_id', models.IntegerField(default=1)),
                ('plant_id', models.IntegerField(default=1)),
                ('process_type', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
