# Generated by Django 3.1.7 on 2021-03-30 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processApp', '0003_product_process'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product_process',
            new_name='process',
        ),
    ]
