# Generated by Django 3.1.7 on 2021-03-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processApp', '0004_auto_20210330_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='project_id',
            field=models.IntegerField(default=1),
        ),
    ]
