# Generated by Django 3.1.7 on 2021-05-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processApp', '0004_auto_20210513_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzed_data',
            name='userID',
            field=models.IntegerField(default=1),
        ),
    ]
