# Generated by Django 3.1.7 on 2021-05-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processApp', '0005_analyzed_data_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzed_data',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
