# Generated by Django 3.1.7 on 2021-04-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processApp', '0005_process_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='一日当り付加価値額収支',
            new_name='付加価値額',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='一日当り必要固定費額',
            new_name='外注費',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='年間必要固定費額',
            new_name='契約金額',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='月間必要固定費額',
            new_name='工事名',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='総付加価値額',
            new_name='材料費',
        ),
        migrations.AddField(
            model_name='projects',
            name='案件名',
            field=models.CharField(default='', max_length=100),
        ),
    ]
