# Generated by Django 3.1.7 on 2021-04-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processApp', '0006_auto_20210401_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='一日当り付加価値額収支',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='projects',
            name='一日当り必要固定費額',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='projects',
            name='年間必要固定費額',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='projects',
            name='月間必要固定費額',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='projects',
            name='総付加価値額',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='added_value_processes',
            name='一台当たりの付加価値額',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='added_value_processes',
            name='目標付加価値額',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='added_value_processes',
            name='目標生産数量',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='added_value_processes',
            name='部材点数',
            field=models.FloatField(default=0.0),
        ),
    ]
