# Generated by Django 3.1.7 on 2021-05-14 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processApp', '0007_auto_20210513_1104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data',
        ),
        migrations.RemoveField(
            model_name='analyzed_data',
            name='dataSetID',
        ),
        migrations.RemoveField(
            model_name='analyzed_data',
            name='typeID',
        ),
        migrations.RemoveField(
            model_name='analyzed_data',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='data_set',
            name='analyzedDataID',
        ),
        migrations.RemoveField(
            model_name='data_set',
            name='dataID',
        ),
        migrations.RemoveField(
            model_name='data_set',
            name='typeID',
        ),
        migrations.RemoveField(
            model_name='data_set',
            name='userID',
        ),
        migrations.AddField(
            model_name='analyzed_data',
            name='data_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='processApp.data_set'),
        ),
        migrations.AddField(
            model_name='analyzed_data',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='indexApp.data_category'),
        ),
        migrations.AddField(
            model_name='analyzed_data',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='data_set',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='indexApp.data_category'),
        ),
        migrations.AddField(
            model_name='data_set',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
