# Generated by Django 3.1.7 on 2021-04-01 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processApp', '0007_auto_20210401_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='案件名',
        ),
    ]
