# Generated by Django 3.1.7 on 2021-04-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processApp', '0008_remove_projects_案件名'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='added_value_processes',
            name='工程',
        ),
        migrations.AddField(
            model_name='added_value_processes',
            name='日あたらりの目標付加価値',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='added_value_processes',
            name='日あたりの目標生産数量',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='process',
            name='一台当たりの付加価値額',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='process',
            name='付加価値額',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='process',
            name='実行予算金額',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='process',
            name='日当りの目標付加価値額',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='process',
            name='日当りの目標生産数量',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='process',
            name='比率',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='process',
            name='部材点数',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='added_value_processes',
            name='付加価値額',
            field=models.FloatField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='added_value_processes',
            name='実行予算金額',
            field=models.FloatField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='added_value_processes',
            name='比率',
            field=models.FloatField(default='', max_length=100),
        ),
    ]
