# Generated by Django 3.1.7 on 2021-05-19 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processApp', '0008_auto_20210514_0426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_set',
            old_name='type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='data_set',
            old_name='categoryID',
            new_name='type_id',
        ),
        migrations.RemoveField(
            model_name='analyzed_data',
            name='type',
        ),
        migrations.RemoveField(
            model_name='data_set',
            name='user',
        ),
    ]
