# Generated by Django 3.1.7 on 2021-04-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processApp', '0009_auto_20210402_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='production_plant_id',
        ),
        migrations.AddField(
            model_name='added_value_processes',
            name='process_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='added_value_processes',
            name='production_plant_id',
            field=models.IntegerField(default=1),
        ),
    ]
