# Generated by Django 3.1.7 on 2021-05-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processApp', '0009_auto_20210519_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_set',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
