# Generated by Django 3.1.7 on 2021-04-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processApp', '0010_auto_20210402_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_process',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('product_id', models.IntegerField(default=1)),
                ('plant_id', models.IntegerField(default=1)),
                ('project_id', models.IntegerField(default=1)),
                ('process_type', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('実行予算金額', models.FloatField(default=0.0)),
                ('比率', models.FloatField(default=0.0)),
                ('付加価値額', models.FloatField(default=0.0)),
                ('部材点数', models.FloatField(default=0.0)),
                ('一台当たりの付加価値額', models.FloatField(default=0.0)),
                ('日当りの目標生産数量', models.FloatField(default=0.0)),
                ('日当りの目標付加価値額', models.FloatField(default=0.0)),
            ],
        ),
        migrations.DeleteModel(
            name='added_value_processes',
        ),
        migrations.RemoveField(
            model_name='products_list',
            name='フロッヒーNO',
        ),
        migrations.RemoveField(
            model_name='products_list',
            name='予算決定者',
        ),
        migrations.RemoveField(
            model_name='products_list',
            name='備考',
        ),
        migrations.RemoveField(
            model_name='products_list',
            name='全材料購入単価',
        ),
        migrations.RemoveField(
            model_name='products_list',
            name='全材料購入重量',
        ),
        migrations.RemoveField(
            model_name='products_list',
            name='受注時値引率',
        ),
        migrations.RemoveField(
            model_name='products_list',
            name='営業担当者',
        ),
        migrations.RemoveField(
            model_name='products_list',
            name='変動費Aの場合の限界利益率',
        ),
        migrations.RemoveField(
            model_name='products_list',
            name='変動費Aの場合の限界利益額',
        ),
        migrations.RemoveField(
            model_name='products_list',
            name='契約金額',
        ),
        migrations.RemoveField(
            model_name='products_list',
            name='契約金額対損益分岐点受注額差',
        ),
        migrations.RemoveField(
            model_name='products_list',
            name='実行売上総利益率',
        ),
        migrations.RemoveField(
            model_name='products_list',
            name='実質経常利益率',
        ),
        migrations.RemoveField(
            model_name='products_list',
            name='工事名',
        ),
        migrations.RemoveField(
            model_name='products_list',
            name='工事担当者',
        ),
        migrations.RemoveField(
            model_name='products_list',
            name='工事番号',
        ),
        migrations.RemoveField(
            model_name='products_list',
            name='工事項目',
        ),
        migrations.RemoveField(
            model_name='products_list',
            name='建方予定日',
        ),
        migrations.RemoveField(
            model_name='products_list',
            name='建設地',
        ),
        migrations.RemoveField(
            model_name='products_list',
            name='得意先',
        ),
        migrations.RemoveField(
            model_name='products_list',
            name='損益分岐受注額',
        ),
        migrations.RemoveField(
            model_name='products_list',
            name='構造_規模_延床',
        ),
        migrations.RemoveField(
            model_name='products_list',
            name='用途',
        ),
        migrations.RemoveField(
            model_name='products_list',
            name='総ton数',
        ),
        migrations.RemoveField(
            model_name='products_list',
            name='裏当金_ピース_ブレースシート等',
        ),
        migrations.RemoveField(
            model_name='products_list',
            name='見積金額',
        ),
        migrations.RemoveField(
            model_name='products_list',
            name='記録日',
        ),
        migrations.RemoveField(
            model_name='products_list',
            name='記録者',
        ),
        migrations.RemoveField(
            model_name='products_list',
            name='設計事務所',
        ),
        migrations.RemoveField(
            model_name='products_list',
            name='部門間接比率',
        ),
    ]
