# Generated by Django 3.1.7 on 2021-06-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processApp', '0010_auto_20210519_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_set',
            name='category',
        ),
        migrations.AddField(
            model_name='data_set',
            name='category_id',
            field=models.IntegerField(default=1),
        ),
    ]
