# Generated by Django 3.1.7 on 2021-04-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processApp', '0011_auto_20210402_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='is_calculate',
            field=models.BooleanField(default=True),
        ),
    ]
