# Generated by Django 3.1.7 on 2021-04-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processApp', '0013_auto_20210403_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='部材点数',
            field=models.IntegerField(default=0),
        ),
    ]
