# Generated by Django 3.1.7 on 2021-04-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processApp', '0014_auto_20210403_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='一台当たりの付加価値額',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='process',
            name='日当りの目標付加価値額',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='process',
            name='日当りの目標生産数量',
            field=models.IntegerField(default=0),
        ),
    ]
