# Generated by Django 3.1.7 on 2021-04-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processApp', '0015_auto_20210403_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='実行予算計画後合計',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='一日当り付加価値額収支',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='一日当り必要固定費額',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='年間必要固定費額',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='月間必要固定費額',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='総付加価値額',
            field=models.IntegerField(default=0),
        ),
    ]
