# Generated by Django 3.1.7 on 2021-04-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processApp', '0016_auto_20210403_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='arise_data',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('project_id', models.IntegerField(default=1)),
                ('value', models.IntegerField(default=1)),
            ],
        ),
    ]
