# Generated by Django 3.1.7 on 2021-04-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processApp', '0018_auto_20210403_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='付加価値額',
            field=models.IntegerField(default=0),
        ),
    ]
