# Generated by Django 3.1.7 on 2021-03-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='production_plant_list',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'indexApp_production_plant_list',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='roles_list',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('access', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='total_cost_list',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
