# Generated by Django 3.1.7 on 2021-03-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='process_list',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('plant_id', models.IntegerField(default=1)),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='product_process_list',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(default='', max_length=200)),
                ('detailed_name', models.CharField(default='', max_length=200)),
                ('id_total_cost', models.IntegerField(default=1)),
                ('default', models.BooleanField(default=True)),
            ],
        ),
    ]
