# Generated by Django 3.1.7 on 2021-03-30 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0002_process_list_product_process_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_process_list',
            old_name='detailed_name',
            new_name='name',
        ),
    ]
