# Generated by Django 3.1.7 on 2021-03-30 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0003_auto_20210330_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_process_list',
            old_name='id_total_cost',
            new_name='id_process',
        ),
    ]
