# Generated by Django 3.1.7 on 2021-04-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0004_auto_20210330_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_list',
            name='process_code',
            field=models.CharField(default='', max_length=200),
        ),
    ]
