# Generated by Django 3.1.7 on 2021-04-01 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0005_process_list_process_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process_list',
            old_name='process_code',
            new_name='大工程番号',
        ),
    ]
