# Generated by Django 3.1.7 on 2021-04-02 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0006_auto_20210402_0231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product_process_list',
            new_name='sub_process_list',
        ),
    ]
