# Generated by Django 3.1.7 on 2021-04-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0007_auto_20210402_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_process_list',
            name='id_process',
            field=models.IntegerField(default=0),
        ),
    ]
