# Generated by Django 3.1.7 on 2021-04-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0008_auto_20210402_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_process_list',
            name='group_name',
        ),
        migrations.AddField(
            model_name='sub_process_list',
            name='程番号',
            field=models.CharField(default='', max_length=200),
        ),
    ]
