# Generated by Django 3.1.7 on 2021-04-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0009_auto_20210402_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_process_list',
            name='is_calculate',
            field=models.BooleanField(default=True),
        ),
    ]
