# Generated by Django 3.1.7 on 2021-03-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210309_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='is_dev',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
