# Generated by Django 3.1.7 on 2021-04-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210325_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='is_dev',
            new_name='is_dev',
        ),
    ]
