# Generated by Django 3.1.7 on 2021-04-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210413_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='company',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='newuser',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=254),
        ),
    ]
